services:
  backend:
    restart: always
    build:
      context: backend
      target: development
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://root:password@mongo:27017/taskmanager
      - JWT_SECRET=mysecretkey
    depends_on:
      - mongo
    networks:
      - my-network

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:5000/api/
    depends_on:
      - backend
    networks:
      - my-network

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=taskmanager
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
    networks:
      - my-network

volumes:
  mongo-data:
    driver: local

networks:
  my-network:
    driver: bridge
